/*
 *  * #%L
 *  * Alfresco Repository
 *  * %%
 *  * Copyright (C) 2005 - 2016 Alfresco Software Limited
 *  * %%
 *  * This file is part of the Alfresco software. 
 *  * If the software was purchased under a paid Alfresco license, the terms of 
 *  * the paid license agreement will prevail.  Otherwise, the software is 
 *  * provided under the following open source license terms:
 *  * 
 *  * Alfresco is free software: you can redistribute it and/or modify
 *  * it under the terms of the GNU Lesser General Public License as published by
 *  * the Free Software Foundation, either version 3 of the License, or
 *  * (at your option) any later version.
 *  * 
 *  * Alfresco is distributed in the hope that it will be useful,
 *  * but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  * GNU Lesser General Public License for more details.
 *  * 
 *  * You should have received a copy of the GNU Lesser General Public License
 *  * along with Alfresco. If not, see <http://www.gnu.org/licenses/>.
 *  * #L%
 */
package com.sourcesense.crl.webservice.opendata.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.1
 * 
 */
@WebService(name = "UpsertOpenDataSoap", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpsertOpenDataSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConnTest", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/ConnTest")
    @WebResult(name = "ConnTestResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "ConnTest", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.ConnTest")
    @ResponseWrapper(localName = "ConnTestResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.ConnTestResponse")
    public String connTest();

    /**
     * 
     * @param privateTOKEN
     * @param odLeggeRegionale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertLR", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertLR")
    @WebResult(name = "UpsertLRResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertLR", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertLR")
    @ResponseWrapper(localName = "UpsertLRResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertLRResponse")
    public String upsertLR(
        @WebParam(name = "ODLeggeRegionale", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odLeggeRegionale,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteLR", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteLR")
    @WebResult(name = "DeleteLRResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteLR", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteLR")
    @ResponseWrapper(localName = "DeleteLRResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteLRResponse")
    public String deleteLR(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odLinkAtti
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertLINK_ATTI", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertLINK_ATTI")
    @WebResult(name = "UpsertLINK_ATTIResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertLINK_ATTI", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertLINKATTI")
    @ResponseWrapper(localName = "UpsertLINK_ATTIResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertLINKATTIResponse")
    public String upsertLINKATTI(
        @WebParam(name = "ODLinkAtti", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odLinkAtti,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteLINK_ATTI", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteLINK_ATTI")
    @WebResult(name = "DeleteLINK_ATTIResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteLINK_ATTI", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteLINKATTI")
    @ResponseWrapper(localName = "DeleteLINK_ATTIResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteLINKATTIResponse")
    public String deleteLINKATTI(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odAtto
     * @param ambiente
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertATTO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertATTO")
    @WebResult(name = "UpsertATTOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertATTO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertATTO")
    @ResponseWrapper(localName = "UpsertATTOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertATTOResponse")
    public String upsertATTO(
        @WebParam(name = "ODAtto", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odAtto,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN,
        @WebParam(name = "ambiente", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String ambiente);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @param ambiente
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteATTO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteATTO")
    @WebResult(name = "DeleteATTOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteATTO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteATTO")
    @ResponseWrapper(localName = "DeleteATTOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteATTOResponse")
    public String deleteATTO(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN,
        @WebParam(name = "ambiente", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String ambiente);

    /**
     * 
     * @param privateTOKEN
     * @param odAttoSI
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertATTO_SI", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertATTO_SI")
    @WebResult(name = "UpsertATTO_SIResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertATTO_SI", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertATTOSI")
    @ResponseWrapper(localName = "UpsertATTO_SIResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertATTOSIResponse")
    public String upsertATTOSI(
        @WebParam(name = "ODAtto_SI", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odAttoSI,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteATTO_SI", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteATTO_SI")
    @WebResult(name = "DeleteATTO_SIResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteATTO_SI", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteATTOSI")
    @ResponseWrapper(localName = "DeleteATTO_SIResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteATTOSIResponse")
    public String deleteATTOSI(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odConsigliere
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertCONS", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertCONS")
    @WebResult(name = "UpsertCONSResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertCONS", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCONS")
    @ResponseWrapper(localName = "UpsertCONSResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCONSResponse")
    public String upsertCONS(
        @WebParam(name = "ODConsigliere", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odConsigliere,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteCONS", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteCONS")
    @WebResult(name = "DeleteCONSResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteCONS", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteCONS")
    @ResponseWrapper(localName = "DeleteCONSResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteCONSResponse")
    public String deleteCONS(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odConsLeg
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertCONS_LEG", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertCONS_LEG")
    @WebResult(name = "UpsertCONS_LEGResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertCONS_LEG", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCONSLEG")
    @ResponseWrapper(localName = "UpsertCONS_LEGResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCONSLEGResponse")
    public String upsertCONSLEG(
        @WebParam(name = "ODCons_Leg", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odConsLeg,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteLINK_CONS_LEG", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteLINK_CONS_LEG")
    @WebResult(name = "DeleteLINK_CONS_LEGResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteLINK_CONS_LEG", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteLINKCONSLEG")
    @ResponseWrapper(localName = "DeleteLINK_CONS_LEGResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteLINKCONSLEGResponse")
    public String deleteLINKCONSLEG(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odOrgano
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertORGANO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertORGANO")
    @WebResult(name = "UpsertORGANOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertORGANO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertORGANO")
    @ResponseWrapper(localName = "UpsertORGANOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertORGANOResponse")
    public String upsertORGANO(
        @WebParam(name = "ODOrgano", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odOrgano,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteORGANO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteORGANO")
    @WebResult(name = "DeleteORGANOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteORGANO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteORGANO")
    @ResponseWrapper(localName = "DeleteORGANOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteORGANOResponse")
    public String deleteORGANO(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odGruppo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertGRUPPO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertGRUPPO")
    @WebResult(name = "UpsertGRUPPOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertGRUPPO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertGRUPPO")
    @ResponseWrapper(localName = "UpsertGRUPPOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertGRUPPOResponse")
    public String upsertGRUPPO(
        @WebParam(name = "ODGruppo", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odGruppo,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteGRUPPO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteGRUPPO")
    @WebResult(name = "DeleteGRUPPOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteGRUPPO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteGRUPPO")
    @ResponseWrapper(localName = "DeleteGRUPPOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteGRUPPOResponse")
    public String deleteGRUPPO(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odComposizioneGruppo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertCOMPOSIZIONE_GRUPPO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertCOMPOSIZIONE_GRUPPO")
    @WebResult(name = "UpsertCOMPOSIZIONE_GRUPPOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertCOMPOSIZIONE_GRUPPO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCOMPOSIZIONEGRUPPO")
    @ResponseWrapper(localName = "UpsertCOMPOSIZIONE_GRUPPOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCOMPOSIZIONEGRUPPOResponse")
    public String upsertCOMPOSIZIONEGRUPPO(
        @WebParam(name = "ODComposizioneGruppo", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odComposizioneGruppo,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteCOMPOSIZIONE_GRUPPO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteCOMPOSIZIONE_GRUPPO")
    @WebResult(name = "DeleteCOMPOSIZIONE_GRUPPOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteCOMPOSIZIONE_GRUPPO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteCOMPOSIZIONEGRUPPO")
    @ResponseWrapper(localName = "DeleteCOMPOSIZIONE_GRUPPOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteCOMPOSIZIONEGRUPPOResponse")
    public String deleteCOMPOSIZIONEGRUPPO(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odDelibera
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertDUP", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertDUP")
    @WebResult(name = "UpsertDUPResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertDUP", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertDUP")
    @ResponseWrapper(localName = "UpsertDUPResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertDUPResponse")
    public String upsertDUP(
        @WebParam(name = "ODDelibera", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odDelibera,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteDUP", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteDUP")
    @WebResult(name = "DeleteDUPResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteDUP", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteDUP")
    @ResponseWrapper(localName = "DeleteDUPResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteDUPResponse")
    public String deleteDUP(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odCalendario
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertCALENDARIO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertCALENDARIO")
    @WebResult(name = "UpsertCALENDARIOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertCALENDARIO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCALENDARIO")
    @ResponseWrapper(localName = "UpsertCALENDARIOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertCALENDARIOResponse")
    public String upsertCALENDARIO(
        @WebParam(name = "ODCalendario", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odCalendario,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteCALENDARIO", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/DeleteCALENDARIO")
    @WebResult(name = "DeleteCALENDARIOResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "DeleteCALENDARIO", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteCALENDARIO")
    @ResponseWrapper(localName = "DeleteCALENDARIOResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.DeleteCALENDARIOResponse")
    public String deleteCALENDARIO(
        @WebParam(name = "ID", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String id,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

    /**
     * 
     * @param privateTOKEN
     * @param odTest
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpsertTest", action = "https://intranet.consiglio.regione.lombardia.it/OpenData/UpsertTest")
    @WebResult(name = "UpsertTestResult", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
    @RequestWrapper(localName = "UpsertTest", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertTest")
    @ResponseWrapper(localName = "UpsertTestResponse", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData", className = "com.sourcesense.crl.webservice.opendata.client.UpsertTestResponse")
    public String upsertTest(
        @WebParam(name = "ODTest", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String odTest,
        @WebParam(name = "PRIVATE_TOKEN", targetNamespace = "https://intranet.consiglio.regione.lombardia.it/OpenData")
        String privateTOKEN);

}
